version: '3.1'

volumes:
    db-data:
        driver: local
    redis-data:
        driver: local

services:
    app:
        build: ./flaskapp/
        image: airhack_app
        volumes:
            - ./flaskapp:/usr/src/app
        ports:
            - "8000:8000"
            - "9191:9191"
        links:
            - db
            - redis
        env_file: .ENV.dev
        command: /usr/local/bin/uwsgi --http-socket 0.0.0.0:8000 --wsgi-file 'app/app_instance.py' --callable app --processes 4 --threads 2 --http-stats 127.0.0.1:9191
    nginx:
        build: ./nginx/
        ports:
            - "80:80"
        volumes:
            - ./flaskapp:/usr/src/app
        links:
            - app:app
    swagger-ui:
        image: swaggerapi/swagger-ui
        ports:
            - 8081:8080
        environment:
            - API_URL=http://35.156.16.182/api/swagger.json
            - PORT=8081
    celery:
        build: ./flaskapp/
        image: airhack_app
        command: make celery
        volumes:
            - ./flaskapp:/usr/src/app
        links:
            - db
            - redis
        env_file: .ENV.dev
    db:
        build:
          ./db/
        ports:
            - ${DB_ENV_PORT:-5432}:5432
        volumes:
            - db-data:/var/lib/postgresql/data
    redis:
        image: redis:4.0.1
        ports:
            - "6390:6390"
        volumes:
          - redis-data:/var/lib/redis
        command: redis-server --bind 0.0.0.0 --port 6390
