"""empty message

Revision ID: 25f946a8b960
Revises: 6c90cec29429
Create Date: 2018-02-01 13:19:09.334477

"""
from alembic import op
import sqlalchemy as sa
import app.extensions
import sqlalchemy_utils
import geoalchemy2
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '25f946a8b960'
down_revision = '6c90cec29429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_profile',
    sa.Column('created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('accomodation', sa.Boolean(), nullable=False),
    sa.Column('transport', sa.Boolean(), nullable=False),
    sa.Column('id', app.database.types.guid.GUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_profile'))
    )
    op.create_table('traveller',
    sa.Column('created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('mobile_number', sa.String(length=255), nullable=False),
    sa.Column('default_accomodation', sa.Boolean(), nullable=False),
    sa.Column('default_transport', sa.Boolean(), nullable=False),
    sa.Column('id', app.database.types.guid.GUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traveller'))
    )
    op.create_table('trip_airports',
    sa.Column('created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('role', sa.Enum('departure', 'arrival', name='airportrole'), nullable=False),
    sa.Column('id', app.database.types.guid.GUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_airports'))
    )
    op.create_table('user_trips',
    sa.Column('created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('id', app.database.types.guid.GUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_trips'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_trips')
    op.drop_table('trip_airports')
    op.drop_table('traveller')
    op.drop_table('search_profile')
    # ### end Alembic commands ###
