"""empty message

Revision ID: b504f1f08205
Revises: a9d597f496f5
Create Date: 2018-02-01 14:11:33.826169

"""
from alembic import op
import sqlalchemy as sa
import app.extensions
import sqlalchemy_utils
import geoalchemy2
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'b504f1f08205'
down_revision = 'a9d597f496f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_airports', sa.Column('iata_code', sa.String(length=3), nullable=False))
    op.add_column('trip_airports', sa.Column('trip_id', app.database.types.guid.GUID(), nullable=False))
    op.create_index(op.f('ix_trip_airports_trip_id'), 'trip_airports', ['trip_id'], unique=False)
    op.create_foreign_key(op.f('fk_trip_airports_trip_id_trip'), 'trip_airports', 'trip', ['trip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_trip_airports_trip_id_trip'), 'trip_airports', type_='foreignkey')
    op.drop_index(op.f('ix_trip_airports_trip_id'), table_name='trip_airports')
    op.drop_column('trip_airports', 'trip_id')
    op.drop_column('trip_airports', 'iata_code')
    # ### end Alembic commands ###
