"""empty message

Revision ID: 6c90cec29429
Revises: 7e5dd2aaf648
Create Date: 2018-02-01 13:02:51.154212

"""
from alembic import op
import sqlalchemy as sa
import app.extensions
import sqlalchemy_utils
import geoalchemy2
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '6c90cec29429'
down_revision = '7e5dd2aaf648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('departure_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.Column('flex_days', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', app.database.types.guid.GUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip'))
    )
    op.add_column('user_token', sa.Column('used', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_token', 'used')
    op.drop_table('trip')
    # ### end Alembic commands ###
