CREATE USER airhack WITH PASSWORD 'Airhack100!';
ALTER USER airhack WITH SUPERUSER;
CREATE DATABASE airhack WITH OWNER airhack ENCODING 'UTF-8';
GRANT ALL PRIVILEGES ON DATABASE "airhack" to airhack;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
